version: '3.7'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: fastbite
      POSTGRES_USER: fastbite
      POSTGRES_PASSWORD: password
    volumes:
      - ./data_db:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d

  payment_service:
    build: .
    environment:
      - AWS_ACCESS_KEY_ID=your_access_key
      - AWS_SECRET_ACCESS_KEY=your_secret_key
      - AWS_DEFAULT_REGION=your_region
    volumes:
      - ./logs:/var/log/shared
    depends_on:
      - db
    ports:
      - "5000:5000"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  node_exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"

  cloudwatch_agent:
    image: amazon/cloudwatch-agent
    volumes:
      - ./cloudwatch-agent-config.json:/etc/cloudwatch-agent-config.json
      - ./logs:/var/log/shared
    command: -config.file=/etc/cloudwatch-agent-config.json