global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'payment_service'
    static_configs:
      - targets: ['payment_service:8000', 'payment_service:8001']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
